config/routes.rb
SpeedTalkWebshop::Application.routes.draw do

  resources :carts

  resources :carts do
    resources :line_items
  end

  resources :discount_groups

  devise_for :users

  root :to => 'products#index'

  resources :categories do
    resources :products
  end

  resources :products do
    resources :ratings, :only => :create
  end

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  attr_accessible :state, :user_id

  belongs_to :user, :touch => true
  has_many :line_items

  def total
    sum = 0
    self.line_items.each do |line_item|
      sum += line_item.total
    end
    sum
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @carts }
    end
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
    @cart = Cart.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cart }
    end
  end

  # GET /carts/new
  # GET /carts/new.json
  def new
    @cart = Cart.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cart }
    end
  end

  # GET /carts/1/edit
  def edit
    @cart = Cart.find(params[:id])
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(params[:cart])

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render json: @cart, status: :created, location: @cart }
      else
        format.html { render action: "new" }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /carts/1
  # PUT /carts/1.json
  def update
    @cart = Cart.find(params[:id])

    respond_to do |format|
      if @cart.update_attributes(params[:cart])
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart = Cart.find(params[:id])
    @cart.destroy

    respond_to do |format|
      format.html { redirect_to :back, notice: 'Cart was successfully deleted.'}
#      format.html { redirect_to carts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.haml
%h3 Cart
%table.table.table-striped
  %thead
    %tr
      %th Product
      %th Quantity
      %th Price
  %tbody
    - cart.line_items.each do |line_item|
      - cache line_item do  
        %tr
          %td
            = link_to line_item.product, category_product_path(line_item.product.category, line_item.product)
          %td{:style => 'white-space: nowrap'}
            = line_item.quantity.to_i
            = link_to(cart_line_item_path(@current_cart, line_item, :quantity => (line_item.quantity + 1)), :method => :put, :class => "btn btn-small") do
              %i.icon-plus
            = link_to(cart_line_item_path(@current_cart, line_item, :quantity => (line_item.quantity - 1)), :method => :put, :class => "btn btn-small") do
              %i.icon-minus

          %td
            = number_to_currency(line_item.total)
      %tr
        %td{:colspan => '2'}
          %strong
            Total
        %td
          = number_to_currency(cart.total)

%p
  = link_to(cart_path(@current_cart), :method => :delete, :class => "btn btn-small") do
    %i.icon-trash
    Delete cart

app/views/carts/_form.html.erb
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<h1>Listing carts</h1>

<table>
  <tr>
    <th>User</th>
    <th>State</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @carts.each do |cart| %>
  <tr>
    <td><%= cart.user_id %></td>
    <td><%= cart.state %></td>
    <td><%= link_to 'Show', cart %></td>
    <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
    <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @cart.user_id %>
</p>

<p>
  <b>State:</b>
  <%= @cart.state %>
</p>


<%= link_to 'Edit', edit_cart_path(@cart) %> |
<%= link_to 'Back', carts_path %>