config/routes.rb
SpeedTalkWebshop::Application.routes.draw do

  resources :carts

  resources :carts do
    resources :line_items
  end

  resources :discount_groups

  devise_for :users

  root :to => 'products#index'

  resources :categories do
    resources :products
  end

  resources :products do
    resources :ratings, :only => :create
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name

  has_many :products

  def to_s
  	self.name.to_s
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])
    spread_breadcrumbs

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new
    spread_breadcrumbs

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
    spread_breadcrumbs
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])
    spread_breadcrumbs

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end

  private
  def spread_breadcrumbs
    add_breadcrumb 'Listing categories', categories_path
    if @category && !@category.new_record?
      add_breadcrumb @category, @category
    end
  end  
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.haml
= form_for(@category) do |f|
  - if @category.errors.any?
    #error_explanation
      %h2
        = pluralize(@category.errors.count, "error")
        prohibited this category from being saved:
      %ul
        - @category.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :name
    %br/
    = f.text_field :name
  .actions
    = f.submit

app/views/categories/edit.html.haml
%h1 Editing category
= render 'form'
= link_to 'Show', @category
|
\#{link_to 'Back', categories_path}

app/views/categories/index.html.haml
%h1 Listing categories
%table.table.table-striped
  %thead
    %tr
      %th Name
      - if user_signed_in?
        %th
        %th
        %th
  %tbody
    - @categories.each do |category|
      %tr
        %td= link_to category.name, category_products_path(category)
        - if user_signed_in?
          %td= link_to 'Show', category
          %td= link_to 'Edit', edit_category_path(category)
          %td= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' }
%br/
- if user_signed_in?
  = link_to 'New Category', new_category_path

app/views/categories/new.html.haml
%h1 New category
= render 'form'
= link_to 'Back', categories_path

app/views/categories/show.html.haml
- content_for :title, @category

%p
  %b Name:
  = @category.name

%p
  =link_to "Listing products of the category #{@category}", category_products_path(@category)

- if user_signed_in?
  = link_to 'Edit', edit_category_path(@category)
  |
  \#{link_to 'Back', categories_path}