config/routes.rb
SpeedTalkWebshop::Application.routes.draw do

  resources :carts

  resources :carts do
    resources :line_items
  end

  resources :discount_groups

  devise_for :users

  root :to => 'products#index'

  resources :categories do
    resources :products
  end

  resources :products do
    resources :ratings, :only => :create
  end

end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :category_id, :description, :name, :price

  belongs_to :category, :touch => true
  has_many :ratings
  has_many :line_items

  def to_s
  	self.name.to_s
  end

  def average_rating
    self.ratings.average(:value).to_i.ceil
  end

  def discounted_price(user = nil)
    if user && user.class == User
      discount = self.price * (user.discount.to_f / 100)
      self.price - discount
    else
      self.price
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # GET /products
  # GET /products.json
  def index
    if params['category_id'] && Category.where(:id => params['category_id']).any?
      @category = Category.where(:id => params['category_id']).first
      @products = @category.products
      spread_breadcrumbs
    else
      @products = Product.limit(25)
    end

    fresh_when :etag => [current_user, @products.order(:updated_at).last]
  end

  # GET /products/1
  # GET /products/1.json
  def show
    if params['category_id'] && Category.where(:id => params['category_id']).any?
      @category = Category.where(:id => params['category_id']).first
    end
    @product = Product.find(params[:id])
    spread_breadcrumbs

    fresh_when :etag => [current_user, @product]
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new
    spread_breadcrumbs

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
    spread_breadcrumbs
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])
    spread_breadcrumbs

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end

  private
  def spread_breadcrumbs
    if @category
      add_breadcrumb 'Listing categories', categories_path
      add_breadcrumb @category, @category
      add_breadcrumb "Listing products of the category #{@category}", category_products_path(@category)
      if @product && !@product.new_record?
        add_breadcrumb @product, category_product_path(@category, @product)
      end
    else
      add_breadcrumb 'Listing products', root_path
      if @product && !@product.new_record?
        add_breadcrumb @product, @product
      end
    end

  end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.haml
= form_for(@product) do |f|
  - if @product.errors.any?
    #error_explanation
      %h2
        = pluralize(@product.errors.count, "error")
        prohibited this product from being saved:
      %ul
        - @product.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :name
    %br/
    = f.text_field :name
  .field
    = f.label :category_id
    %br/
    = f.text_field :category_id
  .field
    = f.label :description
    %br/
    = f.text_area :description
  .field
    = f.label :price
    %br/
    = f.text_field :price
  .actions
    = f.submit

app/views/products/edit.html.haml
%h1 Editing product
= render 'form'
= link_to 'Show', @product
|
\#{link_to 'Back', products_path}

app/views/products/index.html.haml
- if @category
  - content_for :title, "Listing products of the category #{@category}"
- else
  - content_for :title, "Listing of the first #{@products.count} products"

- cache [current_user, @products, 'products_index_table'] do
  %table.table.table-striped{:id => 'products'}
    %thead
      %tr
        %th Name
        %th Category
        %th Description
        %th Price
        %th Rating
        %th
    %tbody
      - @products.each do |product|
        - cache [current_user, product, 'products_index_table_row'] do
          %tr
            %td= link_to product.name, category_product_path(product.category, product)
            %td
              - if @category && @category == product.category
                = product.category
              - else
                = link_to product.category, category_products_path(product.category)            
            %td= product.description
            %td
              - if user_signed_in? && current_user.discount > 0
                = number_to_currency(product.discounted_price(current_user))
                %br
                %strike
                  = number_to_currency(product.price)
              - else
                = number_to_currency(product.price)          
            %td{:style => 'white-space: nowrap'}
              - (1..product.average_rating).each do 
                %i.icon-star
              - (1..(5 - product.average_rating)).each do 
                %i.icon-star-empty
              - if product.ratings.count > 0
                = "(#{product.ratings.count})"
            %td{:style => 'white-space: nowrap'}
              - if user_signed_in? && !@current_cart.line_items.where(:product_id => product.id).any?
                = link_to(cart_line_items_path(@current_cart, :product_id => product.id), :method => :post, :class => "btn btn-small", :id => "add_#{product.id}") do
                  %i.icon-shopping-cart
                  add

%br/
- if user_signed_in?
  = link_to 'New Product', new_product_path

app/views/products/new.html.haml
%h1 New product
= render 'form'
= link_to 'Back', products_path

app/views/products/show.html.haml
- content_for :title, @product
- if !@product.description.blank?
  - content_for :meta_description, truncate(@product.description, :length => 50)

- cache [current_user, @product, 'products_show'] do
  %table.table.table-striped
    %tr
      %td
        %b Category:
      %td
        = link_to @product.category, @product.category
    %tr
      %td
        %b Description:
      %td
        = @product.description
    %tr
      %td
        %b Price:
      %td
        - if user_signed_in? && current_user.discount > 0
          = number_to_currency(@product.discounted_price(current_user))
          %br
          %strike
            = number_to_currency(@product.price)
        - else
          = number_to_currency(@product.price)

        - if user_signed_in? && !@current_cart.line_items.where(:product_id => @product.id).any?
          %p
            = link_to(cart_line_items_path(@current_cart, :product_id => @product.id), :method => :post, :class => "btn btn-small") do
              %i.icon-shopping-cart
              add

  - cache [current_user, @product, 'products_show_ratings_table'] do
    %h2 Ratings

    %table.table.table-striped
      - if @product.ratings.any?
        - @product.ratings.order(:value).reverse_order.each do |rating|
          - cache [rating, 'products_show_ratings_table_row'] do
            %tr
              %td
                = rating.user
              %td
                - (1..rating.value).each do 
                  %i.icon-star
                - (1..(5 - rating.value)).each do 
                  %i.icon-star-empty
      - else
        %tr
          %td{:colspan => '2'}
            This product hasn't been rated yet.

      - if user_signed_in? && !current_user.ratings.where(:product_id => @product.id).any?
        %tr
          %td
            Please rate this product:
          %td
            - (1..5).each do |i|
              = link_to(product_ratings_path(@product, :user_id => current_user.id, :value => i), :method => :post, :id => "product_#{@product}_rating_#{i}") do
                %i.icon-star-empty